/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Writer {
  constructor()
  uint32(value: number): this
  int32(value: number): this
  sint32(value: number): this
  bool(value: boolean): this
  fixed32(value: number): this
  sfixed32(value: number): this
  float(value: number): this
  double(value: number): this
  string(value: string): this
  bytes(value: unknown): this
  raw(value: Buffer): this
  fork(): this
  ldelim(): this
  reset(): this
  finish(): Buffer
  get len(): number
  uint64(value: unknown): this
  int64(value: unknown): this
  sint64(value: unknown): this
  fixed64(value: unknown): this
  sfixed64(value: unknown): this
  static create(): Writer
}
export declare class Reader {
  pos: number
  len: number
  constructor(buffer: unknown)
  static create(buffer: unknown): Reader
  get buf(): Buffer
  uint32(): number
  int32(): number
  sint32(): number
  bool(): boolean
  fixed32(): number
  sfixed32(): number
  float(): number
  double(): number
  bytes(): Buffer
  string(): string
  skip(length?: number | undefined | null): this
  skipType(wireType: number): this
  uint64(): bigint
  int64(): bigint
  sint64(): bigint
  fixed64(): bigint
  sfixed64(): bigint
}
export declare class NativeMessage {
  constructor()
  decode(buffer: Buffer): void
  getCount(id: number): number
  getMessage(id: number, index?: number | undefined | null): NativeMessage | null
  getBytes(id: number, index?: number | undefined | null): object | null
  getString(id: number, index?: number | undefined | null): string | null
  getUint32(id: number, index?: number | undefined | null): number | null
  getFloat(id: number, index?: number | undefined | null): number | null
  getBool(id: number, index?: number | undefined | null): boolean | null
  getInt32(id: number, index?: number | undefined | null): number | null
  getInt64(id: number, index?: number | undefined | null): number | null
  getDouble(id: number, index?: number | undefined | null): number | null
}
export declare class NativeType {
  constructor()
  addField(name: string, id: number, fieldType: string, repeated: boolean, required: boolean, isMap: boolean, keyType?: string | undefined | null, nested?: NativeType | undefined | null): void
  encode(obj: object): Buffer
}
export declare class ManagedMessage {
  constructor()
  clear(): void
  remove(id: number): void
  has(id: number): boolean
  static decode(buffer: Buffer): ManagedMessage
  setInt32(id: number, value: number): void
  setUint32(id: number, value: number): void
  setFloat(id: number, value: number): void
  setDouble(id: number, value: number): void
  setBool(id: number, value: boolean): void
  setInt64(id: number, value: bigint): void
  setUint64(id: number, value: bigint): void
  setSint32(id: number, value: number): void
  setSint64(id: number, value: bigint): void
  setSfixed64(id: number, value: bigint): void
  setFixed64(id: number, value: bigint): void
  setMap(id: number, obj: object, keyType: number, valueType: number): void
  setString(id: number, value: string): void
  setBytes(id: number, value: Buffer): void
  setNested(id: number, msg: ManagedMessage): void
  setGroup(id: number, msg: ManagedMessage): void
  addInt32(id: number, value: number): void
  addString(id: number, value: string): void
  addNested(id: number, msg: ManagedMessage): void
  addGroup(id: number, msg: ManagedMessage): void
  addUint32(id: number, value: number): void
  addInt64(id: number, value: bigint): void
  addUint64(id: number, value: bigint): void
  addSint32(id: number, value: number): void
  addSint64(id: number, value: bigint): void
  addFixed64(id: number, value: bigint): void
  addSfixed64(id: number, value: bigint): void
  addBool(id: number, value: boolean): void
  addFloat(id: number, value: number): void
  addDouble(id: number, value: number): void
  addBytes(id: number, value: Buffer): void
  encode(): Buffer
  getInt32(id: number): number | null
  getUint32(id: number): number | null
  getFloat(id: number): number | null
  getDouble(id: number): number | null
  getInt64(id: number): bigint | null
  getUint64(id: number): bigint | null
  getSint64(id: number): bigint | null
  getSfixed64(id: number): bigint | null
  getBool(id: number): boolean | null
  getString(id: number): string | null
  getBytes(id: number): Buffer | null
  getNested(id: number): ManagedMessage | null
  getMap(id: number, keyType: number, valueType: number): object | null
  getInt32Array(id: number): Array<number> | null
  getUint32Array(id: number): Array<number> | null
  getDoubleArray(id: number): Array<number> | null
  getFloatArray(id: number): Array<number> | null
  getBoolArray(id: number): Array<boolean> | null
  getStringArray(id: number): Array<string> | null
  getBytesArray(id: number): Array<Buffer> | null
  getPackedInt32(id: number): Array<number> | null
  getPackedUint32(id: number): Array<number> | null
  getPackedInt64(id: number): Array<bigint> | null
  getPackedUint64(id: number): Array<bigint> | null
  getPackedSint64(id: number): Array<bigint> | null
  getPackedBool(id: number): Array<boolean> | null
  setPackedInt32(id: number, value: Array<number>): void
  setPackedUint32(id: number, value: Array<number>): void
  setPackedFloat(id: number, value: Array<number>): void
  setPackedDouble(id: number, value: Array<number>): void
  setPackedBool(id: number, value: Array<boolean>): void
  setPackedInt64(id: number, value: Array<bigint>): void
  setPackedUint64(id: number, value: Array<bigint>): void
  setPackedSint32(id: number, value: Array<number>): void
  setPackedSint64(id: number, value: Array<bigint>): void
  addMapEntry(id: number, key: string, value: unknown, keyType: number, valueType: number): void
  addMapEntryMessage(id: number, key: string, value: ManagedMessage, keyType: number): void
  getNestedArray(id: number): Array<ManagedMessage> | null
}
export declare namespace fast_encoder {
  export function registerSchema(opsJs: Array<object>): number
  export function registerSchemaFast(instructions: Array<number>): number
  export function encodeFast(schemaId: number, numerics: Float64Array, nLen: number, longs: BigInt64Array, lLen: number, strings: Uint8Array, sLen: number, output: Uint8Array): number
}
